# Generated by Django 3.2 on 2021-04-06 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('nutriscore', models.TextField()),
                ('product_url', models.TextField()),
                ('image_url', models.TextField()),
                ('fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='matières grasses')),
                ('saturated_fat', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='acides gras saturés')),
                ('sugar', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='sucres')),
                ('salt', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='sel')),
                ('category', models.ManyToManyField(to='nutella.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('old_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='nutella.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='nutella.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
